### ISSUE TITLE
The pep-server incorrectly includes the primary group mapped from the primary fqan in the list of secondary groups

### ISSUE THREAD

**Issue by andreaceccanti** [argus-authz/argus-pep-server#11]
The latest changes to fix the secondary group mapping has introduced a regression whereby 
the mapping code incorrectly maps the primary fqan twice, both as primary group and as secondary group.

```
1.6 code:
DN: CN=Emilis Antanas Rupeika,[...] pFQAN: /cms FQANs: [/cms] 
mapped to POSIX account: PosixAccount{user=cms1425 group=zh}

1.7 code:
DN: CN=Emilis Antanas Rupeika,[...] pFQAN: /cms FQANs: [/cms] 
mapped to POSIX account: PosixAccount{user=cms106 group=zh groups=zh}
```

Related issue: https://ggus.eu/index.php?mode=ticket_info&ticket_id=117125#update#56

**Comment by marcocaberletti** [comment]
Fixed in Argus release 1.7.0
