### ISSUE TITLE
TLS protocol version should be configurable

### ISSUE THREAD

**Issue by andreaceccanti** [argus-authz/argus-pep-server#25]
Currently TLS version is not configurable, and this can cause incompatibilities with certain client libraries (e.g., HTCondor).

**Comment by StewMH** [comment]
Hi,

Is there any update on this? A fix would be very useful for Condor-CE deployment at RAL.

Thanks,
Stewart

**Comment by andreaceccanti** [comment]
Hi Stewart, 

answered in mail, but reporting info here for interested readers: we plan to have a fix for this after the christmas break, end of January at the latest.

Thanks,
Andrea

**Comment by enricovianello** [comment]
PR: https://github.com/argus-authz/argus-pep-server/pull/27
it depends from:
https://github.com/argus-authz/argus-pdp-pep-common/pull/5
https://github.com/argus-authz/argus-parent/pull/5
and it's linked to:
https://github.com/argus-authz/argus-pdp/pull/5

As soon as the tests on nightly rpms are green, we'll proceed to merge all the PRs https://repo.cloud.cnaf.infn.it/#browse/browse:argus:nightly

**Comment by enricovianello** [comment]
Fixed within v1.7.4
