### ISSUE TITLE
Improper synchronization may lead to corrupted mappings in the Gridmapdir

### ISSUE THREAD

**Issue by andreaceccanti** [argus-authz/argus-pep-server#3]
From Maarten description on GGUS:

> When 2 PEPd threads (typically on different hosts) will try to create a
> particular mapping at the same time, they may step on each other and both back
> out of the operation; in such cases it appears that the file representing the
> proxy may be left behind, which then prevents further attempts to map that
> proxy: if the file is present, it _must_ have a link count of 2, else the code
> fails.

Related GGUS ticket:  https://ggus.eu/index.php?mode=ticket_info&ticket_id=117125

**Comment by marcocaberletti** [comment]
Fixed in Argus release 1.7.0
