### ISSUE TITLE
Escape quoted slash characters when parsing grid-mapfile

### ISSUE THREAD

**Issue by enricovianello** [argus-authz/argus-pep-server#9]
> From GGUS Ticket: https://ggus.eu/index.php?mode=ticket_info&ticket_id=120256

Argus DN mapping code does not nicely handle CNs with "internal" slash characters, like in this example:

```
/DC=ch/DC=cern/OU=computers/CN=cmspilot02/vocms080.cern.ch
```

Apparently a slash does not necessarily have to be a field separator, but this method assumes just that:

https://github.com/argus-authz/argus-pep-server/blob/EMI-3/src/main/java/org/glite/authz/pep/obligation/dfpmap/X509MatchStrategy.java#L54

We needed to escape such internal slash characters in the grid-mapfile:

```
"/DC=ch/DC=cern/OU=computers/CN=cmspilot02\\/vocms080.cern.ch" [...]
```

It would be good if such "hacks" could be avoided.

**Comment by marcocaberletti** [comment]
Fixed in Argus release 1.7.0
